### ISSUE TITLE
error with "include all reference columns" option

### ISSUE THREAD

**Issue by yankisimo** [GoogleCloudPlatform/cloud-data-quality#199]
When I declare the optgion of include all reference columns as the documentation define ([reference-columns.yml](https://github.com/GoogleCloudPlatform/cloud-data-quality/blob/8a9083fbdb3723123d203565c916e466eeae6d68/tests/resources/configs/reference_columns/reference-columns.yml))

  INCLUDE_ALL_REFERENCE_COLUMNS:
    include_reference_columns:
      - *

, I have an error: "ERROR while scanning an alias" and the rule never starts.

**Comment by thinhha** [comment]
Hi @yankisimo thanks for your feedback. The link you provided suggests that this error is a YAML parsing error, where the parsing thinks that the * is part of YAML syntax for an alias instead of a clouddq YAML config. I also noticed some indentation issues with your YAML example.

Could you please try either of the configs below and let me know if it works?

[1]
```
  INCLUDE_ALL_REFERENCE_COLUMNS:
    include_reference_columns:
      - *
```

[1]
```
  INCLUDE_ALL_REFERENCE_COLUMNS:
    include_reference_columns:
      - "*"
```

**Comment by thinhha** [comment]
Updated documentations in https://github.com/GoogleCloudPlatform/cloud-data-quality/pull/200

**Comment by yankisimo** [comment]
Hi @thinhha, thanks for your review. 
About my initial syntax, I wrote it as the official documentation said. Probably I wrote the initial comment without any format. 
I confirm that I had it in my original YAML:

   raw_ecommerce_increase_model:
     include_reference_columns:
       - *


And it didn't work. 

But with "*" is ok. 

Thanks

**Comment by yankisimo** [comment]
Closed. Issue resolved. Thanks @thinhha and thanks for your support yesterday with my colleagues.
